// AUTO-GENERATED by tools/generate.js — do not hand-edit.
// To add a game: drop the ROM file in ROMS/<system>/ and run:
//   node tools/generate.js
// To add a system: create ROMS/<newsystem>/, optionally add it to
// SYSTEM_META in tools/generate.js for a nicer name/accent, then run it.
// Games are played via the generic /player.html?system=<id>&rom=<filename>.

const SYSTEMS = [
  {
    id: "megadrive",
    name: "Sega Mega Drive / Genesis",
    short: "Megadrive",
    core: "segaMD",
    emulator: "EmulatorJS · segaMD core",
    accent: "#3ddc97",
    image: "",
    games: [
      { title: "Sonic", image: "", rom: "Sonic.mega" },
      { title: "Sonic 2", image: "", rom: "Sonic2.mega" },
    ],
  },
  {
    id: "n64",
    name: "Nintendo 64",
    short: "N64",
    core: "n64",
    emulator: "EmulatorJS · n64 core",
    accent: "#39ff88",
    image: "",
    games: [
      { title: "Super Mario 64", image: "", rom: "SM64.z64" },
    ],
  },
  {
    id: "snes",
    name: "Super Nintendo",
    short: "SNES",
    core: "snes",
    emulator: "EmulatorJS · snes core",
    accent: "#7c5cff",
    image: "",
    games: [
      { title: "Donkey Kong Country", image: "", rom: "DonkeyKongCountry.sfc" },
    ],
  },
];

// Lookup helper used by console.html and player.html
function getSystem(id) {
  return SYSTEMS.find((s) => s.id === id);
}
